
[gdrive]
type = "service_account"
project_id = "ai-ceo-knowledge-system"
private_key_id = "a5aeb39b36184d1e2834afe8bfbbd99f70712287"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDYLJVQDZ3bV3QF
j8udyjfXWDX3+l2Hcr8af8bUB1qy1uUY5NIgsZwb+fwewwkIvW6098lGhnP8sGkK
LwrRcLvnzfVv2KFDdVmnTnzQmM3iDnjwm66ir+h+wUhdBlg3Zw3wadSgaWF0rIEk
p2Iuo6Vus63F9MimdC+r52U9WrOZJuyEj01mk/VCmvL67FGigPoAVOKdgj3uI3rL
/MeJ27U4T5POWkT9RyE9JWTDIKJA4NjES9ewj0TJB4dbaXOurwdbtGjDM4Qd+EHQ
5LFys06jDYQszVoCGGNNjgNV0E8Q4QNgzY2TkYwT1477vu+7NzuWcIB55Ji3LMlQ
44m5cRHPAgMBAAECggEABN80WkKETT4yUjHEcADvsz28saMF2pieb/VzQLINvDwV
m7MEfVIjZ4oBwZu5p2XFifSPp7Q+BvLe2yjmQIQe6AF/R48FS2ToqVmefIEFGtQi
q6GGlQoL3ldyzw3mjREYglOQRDE7zgpZOr8++jgb8VvBTdXPc9jofiJP6MsTgx8P
2OWdmhl4RpvD9Wzk7YDNNWcjNY6zzN7CaJ3aW3uQ3h0OqSwYQasjXWM2PFvOEqTC
q0LT5ri3sfH7BTuOIyPRxWSg/8xSePA2lF5Vb3e7tlfQnKTN2SlAko5YQEZQpJ5l
3EeGcsjVT+NNSw+ihD5ScYc1DooB/M6BbebnXMcJsQKBgQDtfPejqHSlr6/wnXBd
JfC+d+toqfpQku0diK+qfsTbUrD34QEJxfveAjhmNoSRUpejtRiJHuBbF1VNDGe8
ibVPr3avmtqLhV+SYJ1K6Vki0TMVvqhx0UxBlCCN91q4vtTd47bcSOQEF1EdDrF7
u3+n13aVqXEeVGdQ+wUPilnFaQKBgQDpBkyG9C/iihJBbBGlYb67weVMEr6iukU4
zLO51/jOKp2btss0UvUdWres/OquO0VXBvfUG15rDXDj9Mc9smpkyXat0Uh1WCyd
T+Hd0W0IRmi9Cjy9jxGB89oqjxC6CWrfLMXMGnHkEek1X3WFWjhpTrj+GOOzcRJi
mWhlyXQedwKBgEGSQpHGXkatBogKAE9HvXvpgm8Il5uNpbiE1/PcQqBH6aLXVkEL
kCpRNJ9MKDgztLi3tMmPY+TiwWOfrDjLUOtqh/ueZv8k2SmCUYuweDL7zf4QAVRD
tKlaq85m4H6n+gA18nRKD+LtSTEbsHd4YpvGCvDxstDr/wbF+DS9P2IZAoGBANn4
WWc3TP90NcVaiFsRxm8s3Qa+1fGzmYKbAFcLraFz/X+ligjEvKGbtQosfn1B1gek
7fdLLpOmu/2Pfzu4A4uJY+kNReD1/K2eBmIOPxYpflmuFMkf5bmQV3fN4VCT9JMT
92WHKxeypVmWlICLtw7SY3rT31J/pznx09S6j1LbAoGAdhL2wD42OABLF52EZmzm
udePURJ9hclONzDl/PxjFQ/5nIcKSpO1Oq9DcBGzZoDK9WU79TrCV/VusgeUs7H+
A/k/4U7ltXuIElxPhC9wnOIGKHQOi4t1aUQn8eyHJgg1R4n3uk7T3KnvAnKHtl/R
dzdkiLaN2HTi20Mptyd03jk=
-----END PRIVATE KEY-----"""
client_email = "brain-api-service@ai-ceo-knowledge-system.iam.gserviceaccount.com"
client_id = "102826388525105671841"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/brain-api-service%40ai-ceo-knowledge-system.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
shared_drive_id = "10nW9LN61H03zWADNpUUJKvraOhY-5IoA"

[gdrive2]
type = "service_account"
project_id = "ai-ceo-knowledge-system"
private_key_id = "c92cd655b133a25518e4cb40faf25720a5bc3d48"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCtPuy9eVltrP7d
/2FolmHxZEOhppkMCPYZUeaZsAVbBAMwfvDYLNUN5tI8WjXp3veapF47eORPoyRV
dZrg6r18YyhRkFkS/8mSzeGgVTB+m8rL3HnDbCVZ+tG9bDzNW6pfO1YirhvVioNM
QH+VZ2vdUHye5x+IjvNZTICAt6cU316bIEoHmI2YFZ/N9u6+6drBLWqropAG9+uK
7QpGF2x93BtwjBOG2pDBOnGXWxY0XkwAToI5U2ne1YJEE2rjNAP3K3/25nR5TXub
9nY5IUB7KTVRpApn6OlqRnvgiaaHQouGOzY6kU/qGZB3P4YFOdHV9CynpF7VQZUm
YeWRv9BZAgMBAAECggEACheBZ6elGpcSWSj2WgbxkWPVbzoSzgFLIa40TEVVSIgf
LfDlE3ioGAlXO5IHNDaLbqAOx7Da/tsaY5qIUTwHWfK2P2sUzz8kdTdmQmZX/vYR
DgdLtgMrmVZbp6jBkXZaojXFBpvlDe9Fxvg2XmQCA+g7fC+rNfOa0Bu9XBImqtfg
C9fteBGrwQ1lnxk0FLEtpVGbdRsFZWmovH6mTbN3AjUFLvRfcdzJUlJGN2wGRkj+
EoX48BbPyq4Wy/v/MeAzlNNiACWEpOvhDHMqN46GHUc3yzslLdPSEzQTKehS+8gy
FRjknuQQqYsZdEjuwVcGDX1a5pQ/IXur9WQBOP++wQKBgQDl/g7FL+6MNnn2LP0v
NmDms4B9oY2oaNFfWDjeXaw8Ym2w0MKc4mNAIMSQxaISp7pTAjwlUcUBG6hMRcPb
PMExEGJMkPoqpZOmWUqBMnrD1zwIkfkJ5Xbe14ZYZio1XZi5egpuT9jetIuCStMI
Lbuxggu1UCSrPyx0paikg2XXGQKBgQDA1iLS7DDnOOktfTZSkE38uqqnEUZmwTFX
n4U8ii06xkZdjLa4IiQrDx2Rx2ekry6sdCpJyf4ND91fS7vnzkEJXfdSoM54Yr2z
AW1jyBP4xLqRGFsACr9/x5LGWEiIUMmoHfqq8iBRpsOGgeVijmgUeXdl4tnav8fD
bm2FnzsrQQKBgQCxfvrDL5S4XSqO1HWpRBxQr2OQkWeT+yDqplltM3nDOGtTNCmd
jhHu4dsRp5THNO7VNTpZyttxWXjvNEBNKHwoc26JjLGkzBhBH1QilWStU6SfMJi0
DIVKwaaK/n3ApbVCH2+BZtoGNewc58Yp37Gk8qo6idli1+RlOZwHKukjsQKBgQCd
+M5ebA9D3GNpWIH/8SdyOplCc+xwkSOS3KORjMCwvW03hebJwW5Pt/pJSkmlp71c
mW1rNYZhvPVk8+3jYBv3SHsrvYBnLryowCqU63sw+Di+VG14A1YNn7ils/z3bvdE
Ogr3r5K6URssPY1kx7SL0VX2qXg+s406lGQ0atVWAQKBgQCDVRn85cZbx+AUlHLN
1YUzf9sWjKGN+ntqE9pa0OR2VDK5ytLQHeo+VIpAXIsoHeUUHegYkBMvCyeVH8e6
B/v6ZHX3E1kSY/J50A9vLsxQSbgTMILhRp4be+0h7/zaR9YeLuhybgQtDEa+XrAZ
hx3Dwqg/ObYttW7joFnE66pkqw==
-----END PRIVATE KEY-----"""
client_email = "ai-ceo-drive@ai-ceo-knowledge-system.iam.gserviceaccount.com"
client_id = "105920682971685209118"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ai-ceo-drive%40ai-ceo-knowledge-system.iam.gserviceaccount.com"
universe_domain = "googleapis.com"



